// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Cps1CNlkI24U-lWf_sNcKH3-6Sxm9bc',
    appId: '1:678335233367:web:fa08406a06574d0c8b9212',
    messagingSenderId: '678335233367',
    projectId: 'jobmatch-ai-19248',
    authDomain: 'jobmatch-ai-19248.firebaseapp.com',
    storageBucket: 'jobmatch-ai-19248.firebasestorage.app',
    measurementId: 'G-HGVY1W940Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtT1nmPJ8KpLFLY-jrb9GWDsE2mC9vgEg',
    appId: '1:678335233367:android:91402d2a49b7f5ae8b9212',
    messagingSenderId: '678335233367',
    projectId: 'jobmatch-ai-19248',
    storageBucket: 'jobmatch-ai-19248.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Cps1CNlkI24U-lWf_sNcKH3-6Sxm9bc',
    appId: '1:678335233367:web:bee7aadac2e887768b9212',
    messagingSenderId: '678335233367',
    projectId: 'jobmatch-ai-19248',
    authDomain: 'jobmatch-ai-19248.firebaseapp.com',
    storageBucket: 'jobmatch-ai-19248.firebasestorage.app',
    measurementId: 'G-CDS3JT8JTZ',
  );
}